package com.netease.pharos;

import java.util.concurrent.atomic.AtomicInteger;

/* loaded from: classes2.dex */
public class Const {
    public static final AtomicInteger CACHE_EXPIRE = new AtomicInteger(1800);
    public static final int CHECK_DNS = 5;
    public static final int CHECK_KCP = 3;
    public static final int CHECK_PING = 4;
    public static final int CHECK_TCP = 1;
    public static final int CHECK_UDP = 2;
    public static final int CONNECT_TIMEOUT_TIME = 3000;
    public static final String DEFAULT_NET_DECISION_CONFIG = "default_net_decision_config.txt";
    public static final int FAIL = -1;
    public static final int FINISH = 1;
    public static final String HEADER_HEADER_HOST = "Host";
    public static final String HEADER_RANGE = "Range";
    public static final String HEADER_RANGE_BYTES_PREF = "bytes=";
    public static final String HEADER_RANGE_BYTES_SUFF = "-";
    public static final String HEADER_RANGE_END = "END";
    public static final String HEADER_RANGE_START = "START";
    public static final String HTTP_DNS_SERVER_MAINLAND = "httpdns.nie.netease.com";
    public static final String HTTP_DNS_SERVER_OVERSEA = "httpdns.nie.easebar.com";
    public static final String IF_NONE_MATCH = "If-None-Match";
    public static final int INIT = 0;
    public static final int KCP_PORT = 9997;
    public static final String LAST_LIGHTEN_LOCAL_CONFIG = "last_lighten_local_config.txt";
    public static final String LAST_NET_DECISION_CONFIG = "last_net_decision_config.txt";
    public static final String LAST_REGION_LOCAL_CONFIG = "last_region_local_config.txt";
    public static final String METHOD_DELETE = "DELETE";
    public static final String METHOD_GET = "GET";
    public static final String METHOD_POST = "POST";
    public static final int PROGRESS = 2;
    public static final int PROTODCAL_KCP = 3;
    public static final int PROTODCAL_TCP = 1;
    public static final int PROTODCAL_UDP = 2;
    public static final int QOS_4G_DEFAULT_INT = -11;
    public static final int QOS_4G_FAIL_INT = 0;
    public static final int QOS_4G_NO_SUPPORT = -1;
    public static final int QOS_4G_SUCCESS_INT = 1;
    public static final int QOS_4G_TEST_INT = 2;
    public static final int QOS_CYCLE_DELAY = 1;
    public static final int QOS_CYCLE_INTERVAL = 1;
    public static final String QOS_DEFAULT = "-11";
    public static final String QOS_FAIL = "0";
    public static final String QOS_IS_NOT_ISP = "-10";
    public static final String QOS_NOT_FIT_THRESHOLD = "-9";
    public static final String QOS_NOT_SUPPORT = "-1";
    public static final String QOS_NO_SUPPORT = "-1";
    public static final String QOS_PREGRESS = "11";
    public static final String QOS_SUCCESS = "1";
    public static final String QOS_TEST = "2";
    public static final int READ_TIMEOUT_TIME = 3000;
    public static final int REPORT_DOWNLOAD_NETMON_CONFIG_FIALD = 2;
    public static final int REPORT_LINK_RESULT = 1;
    public static final int REPORT_LVSIP_FAIL = 3;
    public static final String REPORT_URL_MAINLAND = "https://netlink-sigma.proxima.nie.netease.com";
    public static final String REPORT_URL_OVERSEA = "https://netlink-sigma.proxima.nie.easebar.com";
    public static final int TCP_PORT = 9998;
    public static final int TIME_OUT = 800;
    public static final int UDP_PORT = 9999;
    public static final String UPLOAD_FILE_NAME = "upload_file.txt";
    public static final int UPLOAD_FILE_SIZE = 2048;
    public static final int UPLOAD_FILE_SIZE_32 = 32;
    public static final int UPLOAD_FILE_SIZE_512 = 512;
    public static final String UPLOAD_SERVER_IP = "123.58.164.135";
    public static final String VERSION = "2.8.0";
}